/**
 * @brief A polyalphabetic substitution cipher program using Base-3 arithmetic.
 *
 * This program implements a custom encryption algorithm ("Delta-K") that converts
 * text into a trinary format (using glyphs ▲, ▼, ◆). It supports two modes:
 * 1. Standard Mode: A monoalphabetic substitution where each letter maps to a fixed triplet.
 * 2. Delta Mode: A polyalphabetic substitution (Vigenère-style) where the ciphertext
 * is generated by performing modulo-3 addition between the plaintext trits and
 * the key trits.
 *
 * @author agender-nerd (Kazy)
 * @date 2025
 *
 * @note Documentation comments generated by Gemini AI.
 */

#include "Delta_K.hpp"

#include <iostream>
#include <string>

void selectEncrypt();
void selectDecrypt();

/**
 * @brief The main entry point for the Delta-K cipher program.
 * * Handles user interaction, input collection for plaintext and key,
 * validation of the key, and routing to the appropriate encryption function.
 * * @return int Execution status code.
 */
int main() {
    int userInput;

    std::cout << "Welcome to the DELTA-K Cipher Program!" << std::endl;

    do {
        std::cout << "1: Encrypt plaintext" << std::endl << "2: Decrypt ciphertext";
        std::cin >> userInput;
        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

        if (userInput != 1 && userInput != 2) {
            userInput = -1;
            std::cout << "Invalid input. Please try again" << std::endl;
        }
    } while (userInput == -1);

    if (userInput == 1) {
        selectEncrypt();
    } else if (userInput == 2) {
        selectDecrypt();
    }

    return 0;
}

void selectEncrypt() {
    std::string plaintext;
    std::string ciphertext;
    std::string key;

    std::cout << "Please enter plaintext to encode:" << std::endl;
    std::getline(std::cin, plaintext);
    
    do {
        std::cout << "Enter key (0 for normal cipher):" << std::endl;
        std::cin >> key;
        
        if (key == "0") {
            ciphertext = encrypt(plaintext);
        } else if (!keyValidation(key)) {
            std::cout << "Key invalid. Try again." << std::endl;
        } else {
            ciphertext = encrypt(plaintext, key);
        }
    } while (!(keyValidation(key) || key == "0"));

    std::cout << "Encoded ciphertext:" << std::endl;
    std::cout << ciphertext << std::endl;
}

void selectDecrypt() {
    std::string plaintext;
    std::string ciphertext;

    std::cout << "Please enter ciphertext to decode:" << std::endl;
    std::getline(std::cin, ciphertext);

    plaintext = decrypt(ciphertext);

    std::cout << "Decoded plaintext:" << std::endl;
    std::cout << plaintext << std::endl;
}

